import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "./ClientProvider";


export const metadata: Metadata = {
  title: "My First Full stack Project Using Next.js",
  description: "Generated by satya prakash",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
       <ClientProvider>
        {children}
            <Toaster position="top-right" />
        </ClientProvider>
       
        </body>
    </html>
  );
}
